const todosActionTypes = {
  SET_TODOS: 'SET_TODOS',
  SET_NEW_TODO_TEXT: 'SET_NEW_TODO_TEXT',
  ADD_HASH_TAG_FILTERS: 'ADD_HASH_TAG_FILTERS',
  REMOVE_HASH_TAG_FILTER: 'REMOVE_HASH_TAG_FILTER',
  SET_FILTERED_TODOS: 'SET_FILTERED_TODOS',
  CLEAR_STATE: 'CLEAR_STATE',
  MARK_TODO_AS_COMPLETED: 'MARK_TODO_AS_COMPLETED',
  ADD_NEW_TODO: 'ADD_NEW_TODO',
}

export default todosActionTypes
